### ISSUE TITLE
feature request for multiple account

### ISSUE THREAD

**Issue by ETwontPhone** [ipax77/dsweb_desktop#1]
Hi,

so I've been using a smurf to play Direct Strike with a friend because... lets say... he still has a lot to learn.

Rigth now if I want to check each account or the sum of both I have to change it in the setting page or add/remove the second acc each time.

My request would be that, when you have more then 1 account in the setting, a checkbox for each account would appears next to the ''Player'' and ''BeginatZero'' in the chart page and would modify the chart accordingly, allowing for on the fly change.

Thanks!

**Comment by ipax77** [comment]
Hey, my first (official) feature request, yay :)
I added a new Player Filter here:
![playerfilter](https://user-images.githubusercontent.com/46007167/71057936-8463d900-215e-11ea-8b3c-cc1672eb2941.png)

Let me know if you are happy with this implementation! - have fun! :)

**Comment by ETwontPhone** [comment]
Awesome response time!

I am indeed happy but I've also found a bug.

From when you open the app you go  to charts ->filter-> uncheck the bottom account, uncheck the top acc and then you check the top acc, the box for the bottom account will be marked as checked, which it shoudnt. Note I only have 2 accounts.

If instead you check the box for the bottom acc when no boxes are checked, it work as intended.

Thanks again and keep on chuggin'

**Comment by ipax77** [comment]
fixed it - ty for testing! :)
